### ISSUE TITLE
Linux Arm32 Qml.Net.Internal.Interop  libQmlNet.so: undefined symbol: type_info_callbacks_registerCallbacks

### ISSUE THREAD

**Issue by zhangjingru** [pauldotknopf/net-core-qml#223]
qmake qmlnet_native/QmlNet/QmlNet.pro produced libQmlNet.so
libQmlNet.so copy to publish 

root@NanoPi2:/opt/armapp_qmlnet# dotnet QmlDoNet.dll
Hello World!
System.TypeInitializationException: The type initializer for 'Qml.Net.Internal.Interop' threw an exception.
 ---> System.Exception: Symbol could not be loaded: /opt/armapp_qmlnet/libQmlNet.so: undefined symbol: type_info_callbacks_registerCallbacks. Symbol name: type_info_callbacks_registerCallbacks
   at NetNativeLibLoader.Loader.UnixPlatformLoader.LoadSymbol(IntPtr library, String symbolName)
   at Qml.Net.Internal.Interop.LoadDelegates(Object o, IntPtr library, IPlatformLoader loader)
   at Qml.Net.Internal.Interop.LoadInteropType[T](IntPtr library, IPlatformLoader loader)
   at Qml.Net.Internal.Interop..cctor()
   --- End of inner exception stack trace ---
   at Qml.Net.Internal.Interop.get_NetVariantList()
   at Qml.Net.Internal.Qml.NetVariantList..ctor()
   at Qml.Net.QCoreApplication.Create(Int32 type, List`1 args, Int32 flags)
   at Qml.Net.QCoreApplication..ctor(Int32 type, String[] args, Int32 flags)
   at Qml.Net.QGuiApplication..ctor(String[] args, Int32 flags)
   at QmlDoNet.Program.Main(String[] args) in D:\Project\QmlDoNet\QmlDoNet\Program.cs:line 15

qmake qmlnet_native/QmlNet.pro
Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!

**Comment by pauldotknopf** [comment]
If you are using the ```Qml.Net``` package from NuGet, you need to make sure you use the correct commit to build the native libs.

Can you verify that? If you use ```0.10.0``` from NuGet, build the native libs from that tag.

**Comment by zhangjingru** [comment]
> thanks， need native compilation https://github.com/qmlnet/qmlnet-native
