### ISSUE TITLE
Linux armhf 32bit support

### ISSUE THREAD

**Issue by raven-worx** [pauldotknopf/net-core-qml#228]
Hi,
we managed to compile libQmlNet.so for Linux armv7 (32bit). But during runtime we encounter the following runtime exception:

> Unhandled exception. System.Exception: Unsupported target
   at Qml.Net.Runtimes.RuntimeManager.RuntimeTargetToString(RuntimeTarget target)
   at Qml.Net.Runtimes.RuntimeManager.FindQtRuntime(String[] runtimeDirectories, String qtVersion, RuntimeTarget target)
   at Qml.Net.Runtimes.RuntimeManager.FindSuitableQtRuntime(RuntimeSearchLocation runtimeSearchLocation)
   at Qml.Net.Runtimes.RuntimeManager.DiscoverOrDownloadSuitableQtRuntime(RuntimeSearchLocation runtimeSearchLocation)
   at Features.Program.Main(String[] args) in /source/qmlnet-examples/src/Features/Program.cs:line 12

Digging into the source we spotted the explicit check for 64bit pointer width.
https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net/Runtimes/RuntimeManager.cs#L47

What is the need for explicit 64bit?
And is there any chance to easily support 32bit?

**Comment by pauldotknopf** [comment]
If you've manually compiled ```libQmlNet.so``` and it's installed into the proper location (```/usr/lib```, or ```LD_LIBRARY_PATH```), then you shouldn't need to call the ```RuntimeManager.DiscoverOrDownloadSuitableQtRuntime``` anymore.

**Comment by pauldotknopf** [comment]
Using ```RuntimeManager``` is only for using the pre-compiled Qt/lib bits that we manage.

**Comment by raven-worx** [comment]
i built libQmlNet.so by simply invoking `build.sh` and the result was linked against our custom Qt libs (verified by ldd).
Then i built [qmlnet-examples](https://github.com/qmlnet/qmlnet-examples) and run it on the armv7 target device via `dotnet Features.dll` and the exception is raised.

**Comment by pauldotknopf** [comment]
Uncomment the usage of ```RuntimeManager``` in the examples project.

**Comment by raven-worx** [comment]
ok, i uncommented the RuntimeManager line and it works now. thank you!
