### ISSUE TITLE
Support for single file publishing?

### ISSUE THREAD

**Issue by vadi2** [pauldotknopf/net-core-qml#238]
Trying out the .NET 5 version of [single file publishing](https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md), qmlnet on Linux nor on Windows doesn't seem to cooperate well with it:

```
./Hammer 
Unhandled exception. System.TypeInitializationException: The type initializer for 'Qml.Net.Internal.Interop' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'NetNativeLibLoader.PathResolver.DynamicLinkLibraryPathResolver' threw an exception.
 ---> System.ArgumentException: Path cannot be the empty string or all whitespace. (Parameter 'path')
   at System.IO.Directory.GetParent(String path)
   at NetNativeLibLoader.PathResolver.LocalPathResolver..ctor()
   at NetNativeLibLoader.PathResolver.DynamicLinkLibraryPathResolver..cctor()
   --- End of inner exception stack trace ---
   at NetNativeLibLoader.PathResolver.DynamicLinkLibraryPathResolver..ctor(Boolean searchLocalFirst)
   at Qml.Net.Internal.Interop..cctor()
   --- End of inner exception stack trace ---
   at Qml.Net.Internal.Interop.get_QQuickStyle()
   at Qml.Net.QQuickStyle.SetStyle(String style)
   at Program.Main(String[] args)
Aborted (core dumped)
```

**Comment by vadi2** [comment]
Filed as https://github.com/dotnet/runtime/issues/52496.
