### ISSUE TITLE
.NET Framework x.x doesnt work. 

### ISSUE THREAD

**Issue by sethsource** [pauldotknopf/net-core-qml#244]
I've tried using this with every version of .NET framework starting from .net 35 all the way to .net 48 and none of them work. 
I just receive "unsupported target" in my stack trace. I've only had luck using .net core 5 or 6. I've tried transferring the runtimes and I cant get it to run with .net framework x.x

**Comment by sethsource** [comment]
`Unhandled Exception: System.Exception: Unsupported target
   at Qml.Net.Runtimes.RuntimeManager.RuntimeTargetToString(RuntimeTarget target)
   at Qml.Net.Runtimes.RuntimeManager.FindQtRuntime(String[] runtimeDirectories, String qtVersion, RuntimeTarget target)
   at Qml.Net.Runtimes.RuntimeManager.FindSuitableQtRuntime(RuntimeSearchLocation runtimeSearchLocation)
   at Qml.Net.Runtimes.RuntimeManager.DiscoverOrDownloadSuitableQtRuntime(RuntimeSearchLocation runtimeSearchLocation)
   at emailqml.Runner.Main(String[] args) in C:\Users\seth\RiderProjects\emailqml4.8\emailqml4.8\Runner.cs:line 12

Process finished with exit code -532,462,766.

`

**Comment by sethsource** [comment]
`using Qml.Net;
using Qml.Net.Runtimes;
using System;

namespace emailqml 
{
    internal static class Runner
    {
        [STAThread]
        static int Main(string[] args)
        {
            RuntimeManager.DiscoverOrDownloadSuitableQtRuntime();
            QmlNetConfig.ShouldEnsureUIThread = false;
            QQuickStyle.SetStyle("Universal");
            using (QGuiApplication application = new QGuiApplication(args))
            {
                using (QQmlApplicationEngine qmlEngine = new QQmlApplicationEngine())
                {
                    Qml.Net.Qml.RegisterType<Email>("email", 1, 1);
                    qmlEngine.Load("main.qml");
                    return application.Exec();
                }
            }
        }
    }
}`
