### ISSUE TITLE
`RuntimeManager.DiscoverOrDownloadSuitableQtRuntime()` fails on .NET 6.0 

### ISSUE THREAD

**Issue by vadi2** [pauldotknopf/net-core-qml#248]
Using .NET 6.0.302:

```
An unhandled exception of type 'System.Exception' occurred in Qml.Net.dll: 'Couldn't ready block'
   at Qml.Net.Runtimes.Tar.ReadHeader(Stream stream)
   at Qml.Net.Runtimes.Tar.ExtractTarFromGzipStream(Stream stream, String destinationDirectory)
   at Qml.Net.Runtimes.RuntimeManager.GetUrlStream(String url, Action`1 action)
   at Qml.Net.Runtimes.RuntimeManager.DiscoverOrDownloadSuitableQtRuntime(RuntimeSearchLocation runtimeSearchLocation)
```

**Comment by Redforce04** [comment]
Same issue here (roughly)
```
An error has occurred while trying to discover or download a suitable QT runtime. Exception: System.Exception: Couldn't read bytes
   at Qml.Net.Runtimes.Tar.ExtractTarFromGzipStream(Stream stream, String destinationDirectory)
   at Qml.Net.Runtimes.RuntimeManager.GetUrlStream(String url, Action1 action)
   at Qml.Net.Runtimes.RuntimeManager.DiscoverOrDownloadSuitableQtRuntime(RuntimeSearchLocation runtimeSearchLocation)
   at Tarp.Program.Main(String[] args) in C:\Users\redfo\source\repos\Tarp\Tarp\Program.cs

**Comment by ChugunovRoman** [comment]
Same issue (dotnet --version: 7.0.100)
```
Unhandled exception. System.Exception: Couldn't ready block
   at Qml.Net.Runtimes.Tar.ReadHeader(Stream stream)
   at Qml.Net.Runtimes.Tar.ExtractTarFromGzipStream(Stream stream, String destinationDirectory)
   at Qml.Net.Runtimes.RuntimeManager.<>c__DisplayClass7_0.<DownloadRuntimeToDirectory>b__0(Stream stream)
   at Qml.Net.Runtimes.RuntimeManager.GetUrlStream(String url, Action`1 action)
   at Qml.Net.Runtimes.RuntimeManager.DownloadRuntimeToDirectory(String qtVersion, RuntimeTarget runtimeTarget, String destinationDirectory)
   at Qml.Net.Runtimes.RuntimeManager.DiscoverOrDownloadSuitableQtRuntime(RuntimeSearchLocation runtimeSearchLocation)
   at Features.Program.Main(String[] args) in /home/ruut/Projects/qmlnet-examples/src/Features/Program.cs:line 12
```

**Comment by tondrej** [comment]
Can be worked around by downloading and extracting the QT runtime manually:

```
cd ~/.qmlnet-qt-runtimes/
wget https://github.com/qmlnet/qt-runtimes/releases/download/releases/qt-5.15.1-7fc8b10-linux-x64-dev.tar.gz
tar -xvf qt-5.15.1-7fc8b10-linux-x64-dev.tar.gz
```
The version string is [configured](https://github.com/qmlnet/qmlnet/blob/0836ae783a3ed5fb404db68d0706f9a7fa3765b4/src/net/Qml.Net/QmlNetConfig.cs#L9) in `QmlNetConfig.QtBuildVersion`.
